service: auth-server
# app and org for use with dashboard.serverless.com
app: meet
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  timeout: 60 # optional, in seconds, default is 6
  httpApi:
    cors: true
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents # check if this handler is needed
    events:
      - http:
          path: api/get-events/{access_token}
          method: get
        # path: api/get-events/{access_token}/{max_results}
        # maxResults: 32

# you can overwrite defaults here
#  stage: dev
#  region: eu-central-1
